### PR TITLE
[3739587991] Feature/optional logging

### PR DESCRIPTION
**Pull request by HarrisonHough**
## Description

-   Added setting either enable or disable the RPM logger in RPM Settings window under "Other" section. It uses a "ProjectPref" to keep its state in between sessions.              

#### Added

-   Logging enabled setting for SDK logger

## How to Test

-   Add steps to locally test these changes

## Checklist

-   [ ] Tests written or updated for the changes.
-   [ ] Documentation is updated.
-   [ ] Changelog is updated.
-   [ ] QA Testing is updated.

## QA Testing

-   Mention any useful test cases for this feature and add to QA Testing documentation.

## Details

-   If more details are necessary to support the description with images and videos add them here.

### CODE REVIEW

**Comment by rYuuk** [comment]
I would suggest adding an option in settings instead which they could enable and disable easily. As most user will not use it if its a compiler directive which they would need to add in build settings and this will stay disabled forever. 
Also you need to fix the tests for logs as well.

**Comment by HarrisonHough** [comment]
> I would suggest adding an option in settings instead, so developers could enable and disable it easily. As most user will not use it if its a compiler directive which they would need to add in build settings and this will stay disabled forever. Also you need to fix the tests for logs as well.

Yep, good point will add to the settings. Perhaps a combination of settings and prefs to make it stay enabled/disabled.

**Comment by HarrisonHough** [comment]
Updated, not an extra setting in settings window 
image

**Review by rYuuk — APPROVED** [review]
🟢 Great Job and thanks for making the requested change 💯

**Pull request merged**
